### 【総合演習１】賃貸物件情を加工しよう

山手線29駅を最寄り駅に持つ賃貸物件データがあります。  
このデータを使って、賃貸物件の「家賃」の傾向を分析したいと思います。  
分析するための前準備として、基本的なデータ加工を実施していきましょう。  
  
【総合演習の取り組み方】  
* 最初に【Quiestion1】～【Question8】までを実施しましょう。
* 上記問題については、上から順番に実施しましょう。
* 途中「★CHALLENGE★」の記載がありますが、まずは飛ばして実施してください。
* Question問題が完了したら、後続にCHALLENGE問題があるので、実施しましょう。
* 総合演習はテキストを見ながら実施していただいてOKです。

【準備】  
手元にあるのは2つのデータです。  
物件のデータ「room.csv」とその物件の建物のデータ「build.csv」です。  
まずはCSVファイルをテキストエディタで開いてどのようなデータなのか見てみましょう。

---
#### 【Question1】ライブラリをインポートしよう
---

pandasのライブラリをインポートしてください。

In [1]:
# ライブラリインポート
import pandas as pd

---
#### 【Question2】ファイルを読み込もう
---

「build.csv」を読込み、buildという変数に格納してください。  
「room.csv」を読込み、roomという変数に格納してください。※room.csvにはヘッダーがない  
それぞれ読み込んだ変数の先頭5行を表示させて正しく読み込めているか確認しましょう。

In [2]:
# build.csvの読み込みと先頭5行の表示
build = pd.read_csv('data/build.csv')

build.head()

,建物ID,住所1,住所2,住所3,築年数,地上階,地下,沿線1,駅名1,駅徒歩1,沿線2,駅名2,駅徒歩2,沿線3,駅名3,駅徒歩3
0,B0000001,東京都,北区,田端,32,6階建,地下2,ＪＲ山手線,田端駅,6,ＪＲ山手線,西日暮里駅,12.0,東京メトロ千代田線,千駄木駅,16.0
1,B0000002,東京都,台東区,上野,6,14階建,NaN,ＪＲ山手線,秋葉原駅,8,ＪＲ山手線,御徒町駅,5.0,東京メトロ日比谷線,仲御徒町駅,2.0
2,B0000003,東京都,北区,田端,7,2階建,NaN,ＪＲ山手線,駒込駅,9,ＪＲ山手線,田端駅,10.0,ＪＲ山手線,西日暮里駅,14.0
3,B0000004,東京都,北区,田端,23,5階建,NaN,ＪＲ山手線,田端駅,3,東京メトロ千代田線,西日暮里駅,6.0,ＪＲ山手線,日暮里駅,17.0
4,B0000005,東京都,荒川区,東日暮里,13,15階建,NaN,ＪＲ山手線,日暮里駅,2,ＪＲ山手線,西日暮里駅,10.0,ＪＲ山手線,上野駅,25.0

In [3]:
# room.csvの読み込みと先頭5行の表示
room = pd.read_csv('data/room.csv',header=None)

room.head()

          0         1   2     3       4          5     6    7    8
0  R0000001  B0000001  2階   44K  552.58  2484000.0     0  0.0  1.0
1  R0000002  B0000002  7階    1K   26.10   100000.0  8000  1.0  1.0
2  R0000003  B0000002  8階    1K   26.10    99500.0  8000  1.0  1.0
3  R0000004  B0000003  1階  1LDK   40.12   118000.0  5800  0.0  2.0
4  R0000005  B0000004  3階  3LDK   89.67   235000.0     0  2.0  0.0

---
#### 【Question3】roomの列名をつけよう
---

roomはcsvファイルにヘッダーがなかった為、列名が列番号になっています。  
以下の通り、列名をつけましょう。

* 列番号0：物件ID
* 列番号1：建物ID
* 列番号2：物件階
* 列番号3：間取り
* 列番号4：面積
* 列番号5：家賃
* 列番号6：管理費
* 列番号7：敷金
* 列番号8：礼金

##### __【＋α】データフレームの列名の定義__
データフレームの列名は`df.columns`で定義されています。  
buildの列名を表示してみると、リスト形式で出力されます。   
`df.columns`に列名をリスト形式で代入することで列名を定義できます。  
`df.columns = ['列名1', '列名2', …, '列名n']`

In [4]:
# ●buildのカラム名定義を出力して、リスト形式であることを確認
build.columns

Index(['建物ID', '住所1', '住所2', '住所3', '築年数', '地上階', '地下', '沿線1', '駅名1', '駅徒歩1',
       '沿線2', '駅名2', '駅徒歩2', '沿線3', '駅名3', '駅徒歩3'],
      dtype='object')

In [5]:
# roomの列名を付与
room.columns = ['物件ID','建物ID','物件階','間取り','面積','家賃','管理費','敷金','礼金']

# 先頭5行を表示して、正しく列名が設定されているのを確認
room.head()

       物件ID      建物ID 物件階   間取り      面積         家賃   管理費   敷金   礼金
0  R0000001  B0000001  2階   44K  552.58  2484000.0     0  0.0  1.0
1  R0000002  B0000002  7階    1K   26.10   100000.0  8000  1.0  1.0
2  R0000003  B0000002  8階    1K   26.10    99500.0  8000  1.0  1.0
3  R0000004  B0000003  1階  1LDK   40.12   118000.0  5800  0.0  2.0
4  R0000005  B0000004  3階  3LDK   89.67   235000.0     0  2.0  0.0

---
#### 【Question4】データの概要を把握しよう
---

読み込んだデータがどのようなデータなのかをざっくり確認していきます。  
データのサイズや項目の型を確認しましょう。  
要約統計量を出力してどんな値が入ってそうか、その規模感を確認しましょう。  
データをスライスして途中のデータも簡単に確認しましょう。  
確認した結果、どのような気づきがあったかを整理しましょう。

In [6]:
# データのサイズ（行, 列）を確認
print("build:", build.shape)
print("room:", room.shape)

build: (13195, 16)
room: (23846, 9)

In [7]:
# データの項目の型を確認
print("==build dtypes==")
print(build.dtypes)
print("==room dtypes==")
print(room.dtypes)

==build dtypes==
建物ID     object
住所1      object
住所2      object
住所3      object
築年数       int64
地上階      object
地下       object
沿線1      object
駅名1      object
駅徒歩1      int64
沿線2      object
駅名2      object
駅徒歩2    float64
沿線3      object
駅名3      object
駅徒歩3    float64
dtype: object
==room dtypes==
物件ID     object
建物ID     object
物件階      object
間取り      object
面積      float64
家賃      float64
管理費       int64
敷金      float64
礼金      float64
dtype: object

In [8]:
# buildの要約統計量を出力（数値も文字も出力する）
build.describe(include='all')

,建物ID,住所1,住所2,住所3,築年数,地上階,地下,沿線1,駅名1,駅徒歩1,沿線2,駅名2,駅徒歩2,沿線3,駅名3,駅徒歩3
count,13195,13195,13195,13195,13195.000000,13195,1319,13195,13195,13195.000000,13195,13195,13065.000000,13195,13195,12723.000000
unique,13195,1,20,281,NaN,53,7,47,218,NaN,54,241,NaN,54,220,NaN
top,B0011587,東京都,豊島区,池袋,NaN,3階建,地下1,ＪＲ山手線,池袋駅,NaN,ＪＲ山手線,池袋駅,NaN,ＪＲ山手線,池袋駅,NaN
freq,1,13195,2688,310,NaN,2202,1080,6462,711,NaN,4065,515,NaN,4525,527,NaN
mean,NaN,NaN,NaN,NaN,21.755665,NaN,NaN,NaN,NaN,6.850095,NaN,NaN,9.889935,NaN,NaN,13.022243
std,NaN,NaN,NaN,NaN,14.670543,NaN,NaN,NaN,NaN,3.766505,NaN,NaN,4.587382,NaN,NaN,5.585684
min,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,1.000000,NaN,NaN,1.000000
25%,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,7.000000,NaN,NaN,10.000000
50%,NaN,NaN,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,10.000000,NaN,NaN,13.000000
75%,NaN,NaN,NaN,NaN,33.000000,NaN,NaN,NaN,NaN,9.000000,NaN,NaN,12.000000,NaN,NaN,16.000000
max,NaN,NaN,NaN,NaN,95.000000,NaN,NaN,NaN,NaN,45.000000,NaN,NaN,50.000000,NaN,NaN,102.000000

In [9]:
# roomの要約統計量を出力（数値も文字も出力する）
room.describe(include='all')

,物件ID,建物ID,物件階,間取り,面積,家賃,管理費,敷金,礼金
count,23846,23846,23846,23846,23846.000000,2.384200e+04,23846.000000,23846.000000,23846.000000
unique,23846,13027,50,18,NaN,NaN,NaN,NaN,NaN
top,R0007005,B0003609,2階,1K,NaN,NaN,NaN,NaN,NaN
freq,1,62,5017,9604,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,33.780598,1.343090e+05,6609.861780,0.908665,0.839891
std,NaN,NaN,NaN,NaN,20.156636,1.037778e+05,5663.377837,0.635366,0.498182
min,NaN,NaN,NaN,NaN,1.650000,2.000000e+04,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,22.000000,8.200000e+04,3000.000000,1.000000,1.000000
50%,NaN,NaN,NaN,NaN,26.950000,1.070000e+05,6000.000000,1.000000,1.000000
75%,NaN,NaN,NaN,NaN,40.427500,1.500000e+05,10000.000000,1.000000,1.000000
max,NaN,NaN,NaN,NaN,701.000000,2.650000e+06,150000.000000,41.000000,2.500012

##### __【＋α】データフレームの列・行の最大表示数変更__
データフレームは通常だと表示が省略されてしまう為、必要に応じて最大表示数を変更できます。  
あまりたくさん表示すると重たくなるので注意が必要です。   

`pd.set_option('display.max_columns', 50)` # 最大表示列数の指定（ここでは50列を指定）  
`pd.get_option("display.max_columns")` # 現在の最大表示列数の出力  
`pd.set_option('display.max_rows', 50)` # 最大表示行数の指定（ここでは50行を指定）  
`pd.get_option("display.max_rows")` # 現在の最大表示行数の出力

In [10]:
# 最大表示行数の指定（ここでは100行を指定）   
pd.set_option('display.max_rows', 100)

# 現在の最大表示行数の出力  
pd.get_option("display.max_rows")

100

In [11]:
# buildやroomをスライスして、任意の途中行を確認しましょう。
# 最大表示数を越えていると前後計10行で省略されてしまうので注意。
build[1000: 1050]
# room[1000:1050]

,建物ID,住所1,住所2,住所3,築年数,地上階,地下,沿線1,駅名1,駅徒歩1,沿線2,駅名2,駅徒歩2,沿線3,駅名3,駅徒歩3
1000,B0001002,東京都,豊島区,西池袋,19,4階建,NaN,ＪＲ山手線,池袋駅,8,ＪＲ山手線,目白駅,9.0,西武池袋線,椎名町駅,14.0
1001,B0001003,東京都,豊島区,西池袋,19,4階建,NaN,ＪＲ山手線,池袋駅,8,ＪＲ山手線,目白駅,9.0,東京メトロ有楽町線,要町駅,15.0
1002,B0001004,東京都,文京区,本駒込,29,10階建,地下1,ＪＲ山手線,駒込駅,5,都営三田線,千石駅,7.0,東京メトロ南北線,本駒込駅,14.0
1003,B0001005,東京都,渋谷区,恵比寿西,35,10階建,NaN,ＪＲ山手線,恵比寿駅,8,東急東横線,代官山駅,7.0,京王井の頭線,渋谷駅,8.0
1004,B0001006,東京都,渋谷区,恵比寿西,35,10階建,NaN,ＪＲ山手線,恵比寿駅,8,東急東横線,代官山駅,8.0,ＪＲ山手線,渋谷駅,12.0
1005,B0001007,東京都,台東区,台東,14,12階建,NaN,都営大江戸線,新御徒町駅,6,ＪＲ山手線,御徒町駅,9.0,東京メトロ日比谷線,秋葉原駅,11.0
1006,B0001008,東京都,台東区,台東,14,12階建,NaN,都営大江戸線,新御徒町駅,6,東京メトロ日比谷線,仲御徒町駅,10.0,ＪＲ山手線,秋葉原駅,12.0
1007,B0001009,東京都,目黒区,下目黒,33,5階建,NaN,ＪＲ山手線,目黒駅,3,東急目黒線,不動前駅,20.0,ＪＲ山手線,五反田駅,20.0
1008,B0001010,東京都,渋谷区,東,2,3階建,NaN,ＪＲ山手線,恵比寿駅,6,東急東横線,代官山駅,11.0,ＪＲ山手線,渋谷駅,17.0
1009,B0001011,東京都,渋谷区,恵比寿,4,5階建,地下1,ＪＲ山手線,恵比寿駅,10,東京メトロ日比谷線,広尾駅,14.0,東京メトロ南北線,白金台駅,14.0
1010,B0001012,東京都,千代田区,外神田,14,15階建,地下1,東京メトロ銀座線,末広町駅,2,ＪＲ山手線,秋葉原駅,5.0,東京メトロ千代田線,湯島駅,9.0
1011,B0001013,東京都,荒川区,西日暮里,3,15階建,地下1,ＪＲ山手線,日暮里駅,3,ＪＲ山手線,西日暮里駅,7.0,日暮里・舎人ライナー,日暮里駅,2.0
1012,B0001014,東京都,豊島区,巣鴨,13,5階建,NaN,ＪＲ山手線,大塚駅,8,都営三田線,西巣鴨駅,9.0,ＪＲ山手線,巣鴨駅,13.0
1013,B0001015,東京都,台東区,下谷,7,14階建,NaN,ＪＲ山手線,上野駅,7,東京メトロ日比谷線,入谷駅,6.0,ＪＲ山手線,鶯谷駅,10.0
1014,B0001016,東京都,北区,田端新町,46,4階建,NaN,ＪＲ山手線,田端駅,11,ＪＲ山手線,西日暮里駅,9.0,京成本線,新三河島駅,10.0
1015,B0001017,東京都,新宿区,大久保,4,37階建,地下2,ＪＲ山手線,高田馬場駅,5,東京メトロ副都心線,西早稲田駅,7.0,ＪＲ山手線,新大久保駅,11.0
1016,B0001018,東京都,千代田区,外神田,14,15階建,地下1,ＪＲ山手線,秋葉原駅,5,東京メトロ銀座線,末広町駅,2.0,東京メトロ千代田線,湯島駅,9.0
1017,B0001019,東京都,豊島区,巣鴨,3,3階建,NaN,ＪＲ山手線,巣鴨駅,2,都電荒川線,巣鴨新田駅,11.0,ＪＲ山手線,大塚駅,11.0
1018,B0001020,東京都,台東区,根岸,4,11階建,NaN,ＪＲ山手線,鶯谷駅,3,ＪＲ山手線,日暮里駅,8.0,東京メトロ日比谷線,入谷駅,12.0
1019,B0001021,東京都,豊島区,西池袋,0,11階建,NaN,ＪＲ山手線,池袋駅,10,東京メトロ有楽町線,要町駅,4.0,ＪＲ山手線,目白駅,19.0
1020,B0001022,東京都,新宿区,北新宿,13,15階建,NaN,ＪＲ山手線,新宿駅,12,東京メトロ丸ノ内線,西新宿駅,7.0,ＪＲ中央線,大久保駅,5.0
1021,B0001023,東京都,豊島区,西池袋,16,2階建,NaN,ＪＲ山手線,池袋駅,9,東京メトロ丸ノ内線,池袋駅,9.0,東京メトロ有楽町線,池袋駅,9.0
1022,B0001024,東京都,渋谷区,神南,21,16階建,NaN,ＪＲ山手線,渋谷駅,8,東京メトロ銀座線,渋谷駅,8.0,東急東横線,渋谷駅,9.0
1023,B0001025,東京都,荒川区,西日暮里,29,5階建,NaN,ＪＲ山手線,日暮里駅,5,ＪＲ山手線,西日暮里駅,7.0,ＪＲ常磐線,三河島駅,9.0
1024,B0001026,東京都,目黒区,三田,1,5階建,NaN,湘南新宿ライン宇須,恵比寿駅,10,東急目黒線,目黒駅,11.0,東急東横線,中目黒駅,14.0
1025,B0001027,東京都,文京区,千駄木,3,3階建,NaN,ＪＲ山手線,西日暮里駅,8,東京メトロ千代田線,千駄木駅,9.0,ＪＲ京浜東北線,田端駅,11.0
1026,B0001028,東京都,台東区,根岸,31,5階建,NaN,ＪＲ山手線,日暮里駅,10,ＪＲ京浜東北線,鶯谷駅,5.0,東京メトロ日比谷線,入谷駅,11.0
1027,B0001029,東京都,台東区,北上野,0,15階建,NaN,東京メトロ日比谷線,入谷駅,4,ＪＲ山手線,上野駅,9.0,東京メトロ銀座線,稲荷町駅,10.0
1028,B0001030,東京都,台東区,上野桜木,25,4階建,NaN,東京メトロ千代田線,根津駅,11,ＪＲ山手線,鶯谷駅,9.0,ＪＲ山手線,日暮里駅,12.0
1029,B0001031,東京都,北区,田端新町,13,15階建,NaN,ＪＲ山手線,田端駅,7,日暮里・舎人ライナー,赤土小学校前駅,8.0,ＪＲ京浜東北線,西日暮里駅,16.0
1030,B0001032,東京都,豊島区,南大塚,14,8階建,NaN,ＪＲ山手線,巣鴨駅,12,東京メトロ丸ノ内線,新大塚駅,6.0,ＪＲ山手線,大塚駅,5.0
1031,B0001033,東京都,渋谷区,恵比寿,23,3階建,NaN,ＪＲ山手線,恵比寿駅,10,東京メトロ日比谷線,広尾駅,15.0,ＪＲ山手線,目黒駅,18.0
1032,B0001034,東京都,台東区,根岸,36,11階建,NaN,ＪＲ山手線,鶯谷駅,4,ＪＲ山手線,日暮里駅,12.0,東京メトロ日比谷線,入谷駅,8.0
1033,B0001035,東京都,荒川区,西日暮里,12,13階建,NaN,ＪＲ山手線,西日暮里駅,4,ＪＲ山手線,日暮里駅,7.0,ＪＲ常磐線,三河島駅,10.0
1034,B0001036,東京都,台東区,台東,12,9階建,NaN,ＪＲ山手線,御徒町駅,8,東京メトロ日比谷線,秋葉原駅,9.0,都営大江戸線,新御徒町駅,10.0
1035,B0001037,東京都,目黒区,下目黒,43,2階建,NaN,東急目黒線,不動前駅,6,ＪＲ山手線,目黒駅,12.0,ＪＲ山手線,五反田駅,16.0
1036,B0001038,東京都,品川区,東五反田,28,3階建,NaN,都営浅草線,高輪台駅,4,ＪＲ山手線,五反田駅,10.0,ＪＲ京浜東北線,品川駅,16.0
1037,B0001039,東京都,目黒区,三田,5,2階建,NaN,ＪＲ山手線,恵比寿駅,10,東京メトロ南北線,目黒駅,10.0,東京メトロ日比谷線,中目黒駅,16.0
1038,B0001040,東京都,渋谷区,宇田川町,6,13階建,NaN,東急東横線,渋谷駅,5,京王井の頭線,神泉駅,12.0,ＪＲ山手線,原宿駅,12.0
1039,B0001041,東京都,荒川区,西日暮里,0,3階建,NaN,東京メトロ千代田線,西日暮里駅,4,ＪＲ山手線,西日暮里駅,6.0,ＪＲ山手線,日暮里駅,6.0
1040,B0001042,東京都,千代田区,岩本町,12,13階建,NaN,都営新宿線,岩本町駅,4,東京メトロ日比谷線,秋葉原駅,5.0,ＪＲ総武線快速,馬喰町駅,5.0
1041,B0001043,東京都,文京区,千石,29,3階建,NaN,都営三田線,千石駅,3,ＪＲ山手線,巣鴨駅,8.0,ＪＲ山手線,駒込駅,14.0
1042,B0001044,東京都,台東区,東上野,2,14階建,NaN,ＪＲ山手線,上野駅,5,東京メトロ銀座線,稲荷町駅,5.0,都営大江戸線,新御徒町駅,13.0
1043,B0001045,東京都,北区,田端,21,6階建,NaN,ＪＲ山手線,駒込駅,7,ＪＲ山手線,田端駅,15.0,都営三田線,千石駅,17.0
1044,B0001046,東京都,目黒区,三田,40,11階建,NaN,ＪＲ山手線,恵比寿駅,10,東京メトロ日比谷線,恵比寿駅,10.0,ＪＲ山手線,目黒駅,10.0
1045,B0001047,東京都,豊島区,南池袋,22,3階建,NaN,ＪＲ山手線,池袋駅,5,ＪＲ山手線,目白駅,6.0,東京メトロ副都心線,雑司が谷駅,8.0
1046,B0001048,東京都,豊島区,目白,20,3階建,NaN,ＪＲ山手線,目白駅,4,東京メトロ有楽町線,池袋駅,15.0,東京メトロ副都心線,池袋駅,15.0
1047,B0001049,東京都,渋谷区,恵比寿西,19,8階建,地下1,ＪＲ山手線,恵比寿駅,4,東急東横線,代官山駅,5.0,東急東横線,中目黒駅,13.0
1048,B0001050,東京都,豊島区,北大塚,25,4階建,NaN,ＪＲ山手線,大塚駅,6,都営三田線,巣鴨駅,8.0,都電荒川線,大塚駅前駅,6.0
1049,B0001051,東京都,渋谷区,代官山町,45,9階建,NaN,ＪＲ山手線,渋谷駅,5,東急東横線,代官山町駅,8.0,東京メトロ日比谷線,恵比寿駅,10.0

【ここに気づきを書いてみましょう】  
* XXXXXX
* XXXXXX

---
#### 【Question5】データクレンジングをしよう
---

##### １）「家賃」が欠損しているデータを削除する
要約統計量を確認すると、今回の分析でキーとなるroomの「家賃」が欠損しているデータがありそうです。  
データが欠損している場合、値補完をするかレコード削除をするか考える必要があります。  
その判断にはその欠損に意味があるかでも対応が異なります。（例えばbuildの「地下」は建物に地下がないと欠損している=意味のある欠損）  
roomの「家賃」については、入力不備等の理由で欠損しているみたいなので（本当はちゃんと確認が必要）、レコードを削除する対応にします。

In [12]:
# roomについて欠損値の有無（数）を確認
room.isnull().sum()

物件ID    0
建物ID    0
物件階     0
間取り     0
面積      0
家賃      4
管理費     0
敷金      0
礼金      0
dtype: int64

##### __【＋α】特定の列が欠損している行を削除する__
欠損がある行を削除するには`df.dropna()`を使用します。  
特定の列の欠損を指定する場合は、以下のように記述します。  

`df.dropna(subset=['A', 'B'])` # 列 A または B に欠損値を含む行を削除する

In [13]:
# 家賃が欠損している行を削除してデータを更新（変数room自体を更新）
room.dropna(subset=['家賃'], inplace=True)

In [14]:
# roomのデータサイズ（行・列）を出力し、欠損が削除されていることを確認
room.shape

(23842, 9)

##### __２）「地下」が欠損しているデータを補完する__
buildの「地下」も欠損しています。  
有識者に確認したところ、賃貸物件に地下が存在していないデータが欠損値となっているそうです。   
欠損のまま扱う場合もありますが、今回は欠損値を'地下0'で置換して補完しましょう。

In [15]:
# buildについて欠損値の有無（数）を確認
build.isnull().sum()

建物ID        0
住所1         0
住所2         0
住所3         0
築年数         0
地上階         0
地下      11876
沿線1         0
駅名1         0
駅徒歩1        0
沿線2         0
駅名2         0
駅徒歩2      130
沿線3         0
駅名3         0
駅徒歩3      472
dtype: int64

In [17]:
# 地下が欠損している場合は、'地下0'に置き換えて、データを更新
# build['地下'].fillna('地下0', inplace=True)

##### __★CHALLENGE２★__
以下に、CHALLENGE２の処理を追加してください。

In [18]:
# buildの「地下」が欠損している場合は0に、それ以外は1に置き換えて、データを更新
build.loc[build['地下'].notnull(), '地下'] = 1
build['地下'].fillna(0, inplace=True)
# buildの「地下」を度数集計して確認
build['地下'].value_counts()

1    13195
Name: 地下, dtype: int64

##### __（★CHALLENGE２★終わり）__

In [19]:
# buildの末尾5行を表示して、欠損が保管されているか確認
build.tail()

,建物ID,住所1,住所2,住所3,築年数,地上階,地下,沿線1,駅名1,駅徒歩1,沿線2,駅名2,駅徒歩2,沿線3,駅名3,駅徒歩3
13190,B0013222,東京都,豊島区,池袋,41,4階建,1,ＪＲ山手線,池袋駅,13,東武東上線,北池袋駅,12.0,東武東上線,下板橋駅,16.0
13191,B0013223,東京都,豊島区,池袋本町,28,4階建,1,ＪＲ山手線,池袋駅,17,東武東上線,北池袋駅,4.0,ＪＲ埼京線,板橋駅,13.0
13192,B0013224,東京都,豊島区,上池袋,12,2階建,1,ＪＲ山手線,池袋駅,21,ＪＲ埼京線,板橋駅,9.0,東武東上線,下板橋駅,14.0
13193,B0013225,東京都,豊島区,池袋,55,2階建,1,ＪＲ山手線,池袋駅,10,東武東上線,北池袋駅,11.0,東武東上線,下板橋駅,16.0
13194,B0013226,東京都,豊島区,池袋本町,27,3階建,1,ＪＲ山手線,池袋駅,18,東武東上線,下板橋駅,10.0,東武東上線,北池袋駅,11.0

In [20]:
# buildの「地下」について欠損値の有無（数）を確認
build['地下'].isnull().sum()

0

##### __３）「間取り」の表記を合わせる__
間取りを確認すると表記ゆれがあります。'ワンルーム'と'1R'はどちらも同じ間取りですが、どちらの表記も出現しています。  
このままだと別々で扱われてしまうので、どちらかの表記にあわせたほうが良いでしょう。  
今回は他の表記と表側をとって'1R'に統一していきましょう。

In [21]:
# roomの「間取り」を度数集計する
room['間取り'].value_counts()

1K       9603
ワンルーム    4311
1LDK     3906
2LDK     1788
1DK      1684
2DK       808
3LDK      492
2K        472
1R        200
1SLDK     176
3DK       121
2SLDK     106
4LDK       60
1SK        46
3SLDK      33
1SDK       18
3K         17
44K         1
Name: 間取り, dtype: int64

In [22]:
# roomの「間取り」が'ワンルーム'という条件のデータを'1R'に変換する
room.loc[room['間取り'] == 'ワンルーム', '間取り'] = '1R'

In [23]:
# roomの「間取り」を度数集計して、表記ゆれが解消されているのを確認
room['間取り'].value_counts()

1K       9603
1R       4511
1LDK     3906
2LDK     1788
1DK      1684
2DK       808
3LDK      492
2K        472
1SLDK     176
3DK       121
2SLDK     106
4LDK       60
1SK        46
3SLDK      33
1SDK       18
3K         17
44K         1
Name: 間取り, dtype: int64

##### __★CHALLENGE１★__
以下に、CHALLENGE１の処理を追加してください。

In [24]:
# buildの「地上階」の'階建'を置換で削除
build['地上階'] = build['地上階'].str.replace('階建', '')
#build.replace({'地上階':{'階建':''}},regex=True)

# 型の確認
print(build.dtypes)
# 型変換（obuject → int）
build = build.astype({'地上階' : int}, copy=True)

# 型の確認
print(build.dtypes)
# 最初の5行を確認
build.head()

建物ID     object
住所1      object
住所2      object
住所3      object
築年数       int64
地上階      object
地下        int64
沿線1      object
駅名1      object
駅徒歩1      int64
沿線2      object
駅名2      object
駅徒歩2    float64
沿線3      object
駅名3      object
駅徒歩3    float64
dtype: object
建物ID     object
住所1      object
住所2      object
住所3      object
築年数       int64
地上階       int32
地下        int64
沿線1      object
駅名1      object
駅徒歩1      int64
沿線2      object
駅名2      object
駅徒歩2    float64
沿線3      object
駅名3      object
駅徒歩3    float64
dtype: object

,建物ID,住所1,住所2,住所3,築年数,地上階,地下,沿線1,駅名1,駅徒歩1,沿線2,駅名2,駅徒歩2,沿線3,駅名3,駅徒歩3
0,B0000001,東京都,北区,田端,32,6,1,ＪＲ山手線,田端駅,6,ＪＲ山手線,西日暮里駅,12.0,東京メトロ千代田線,千駄木駅,16.0
1,B0000002,東京都,台東区,上野,6,14,1,ＪＲ山手線,秋葉原駅,8,ＪＲ山手線,御徒町駅,5.0,東京メトロ日比谷線,仲御徒町駅,2.0
2,B0000003,東京都,北区,田端,7,2,1,ＪＲ山手線,駒込駅,9,ＪＲ山手線,田端駅,10.0,ＪＲ山手線,西日暮里駅,14.0
3,B0000004,東京都,北区,田端,23,5,1,ＪＲ山手線,田端駅,3,東京メトロ千代田線,西日暮里駅,6.0,ＪＲ山手線,日暮里駅,17.0
4,B0000005,東京都,荒川区,東日暮里,13,15,1,ＪＲ山手線,日暮里駅,2,ＪＲ山手線,西日暮里駅,10.0,ＪＲ山手線,上野駅,25.0

In [25]:
# roomの「物件階」の'階'を置換で削除
room['物件階'] = room['物件階'].str.replace('階', '')
#room.replace({'物件階':{'階':''}},regex=True)
# 型の確認
print(room.dtypes)
# 型変換（obuject → int）
room = room.astype({'物件階' : int}, copy=True)

# 型の確認
print(room.dtypes)
# 最初の5行を確認
room.head()

物件ID     object
建物ID     object
物件階      object
間取り      object
面積      float64
家賃      float64
管理費       int64
敷金      float64
礼金      float64
dtype: object
物件ID     object
建物ID     object
物件階       int32
間取り      object
面積      float64
家賃      float64
管理費       int64
敷金      float64
礼金      float64
dtype: object

       物件ID      建物ID  物件階   間取り      面積         家賃   管理費   敷金   礼金
0  R0000001  B0000001    2   44K  552.58  2484000.0     0  0.0  1.0
1  R0000002  B0000002    7    1K   26.10   100000.0  8000  1.0  1.0
2  R0000003  B0000002    8    1K   26.10    99500.0  8000  1.0  1.0
3  R0000004  B0000003    1  1LDK   40.12   118000.0  5800  0.0  2.0
4  R0000005  B0000004    3  3LDK   89.67   235000.0     0  2.0  0.0

##### __（★CHALLENGE１★終わり）__

##### __★CHALLENGE３★__
以下に、CHALLENGE３の処理を追加してください。

In [26]:
# 山手線沿線駅をリストで入力
yamanote = ['大崎駅', '五反田駅', '目黒駅', '恵比寿駅', '渋谷駅', '原宿駅', '代々木駅', 
            '新宿駅', '新大久保駅', '高田馬場駅', '目白駅', '池袋駅', '大塚駅', '巣鴨駅', 
            '駒込駅', '田端駅', '西日暮里駅', '鶯谷駅', '上野駅', '御徒町駅', '秋葉原駅', 
            '神田駅', '東京駅', '有楽町駅', '新橋駅', '浜松町駅', '田町駅', '品川駅']

In [27]:
# 沿線1～沿線3について、山手線駅でか沿線名がＪＲ山手線でないものを置換
build.loc[(build['駅名1'].isin(yamanote)) & (build['沿線1'] != 'ＪＲ山手線'), '沿線1'] = 'ＪＲ山手線'
build.loc[(build['駅名2'].isin(yamanote)) & (build['沿線2'] != 'ＪＲ山手線'), '沿線2'] = 'ＪＲ山手線'
build.loc[(build['駅名3'].isin(yamanote)) & (build['沿線3'] != 'ＪＲ山手線'), '沿線3'] = 'ＪＲ山手線'

##### __（★CHALLENGE３★終わり）__

---
#### 【Question6】データから新規項目を作成しよう
---

##### __１）1㎡あたりの家賃を表す項目を作成する__
賃貸物件は狭い物件も広い物件もある。しかし立地によって地価は異なる為、1㎡あたりの家賃に傾向があるかもしれないという仮説を立てました。  
（もちろん間取り等の様々な影響も十分にあると考えられるけど・・・）  
仮説の検証の為に、1㎡あたりの家賃を計算して新規項目を作成しましょう。

In [28]:
# roomのデータフレームに対して、1㎡あたりの家賃を計算し'平米単価'という名前の列を追加
room['平米単価'] = room['家賃'] / room['面積']

# 先頭5行を表示して、新規項目が追加されたことを確認する
room.head()

,物件ID,建物ID,物件階,間取り,面積,家賃,管理費,敷金,礼金,平米単価
0,R0000001,B0000001,2,44K,552.58,2484000.0,0,0.0,1.0,4495.276702
1,R0000002,B0000002,7,1K,26.10,100000.0,8000,1.0,1.0,3831.417625
2,R0000003,B0000002,8,1K,26.10,99500.0,8000,1.0,1.0,3812.260536
3,R0000004,B0000003,1,1LDK,40.12,118000.0,5800,0.0,2.0,2941.176471
4,R0000005,B0000004,3,3LDK,89.67,235000.0,0,2.0,0.0,2620.720419

##### __２）最も近い駅まで何分かかるかを表す項目を作成する__

In [29]:
# buildの3駅の徒歩時間で最も短い時間を'駅徒歩最短'という名前の列で追加
build['駅徒歩最短'] = build[['駅徒歩1', '駅徒歩2', '駅徒歩3']].min(axis=1)

# 先頭5行を表示して、新規項目が追加されたことを確認する
build.head()

,建物ID,住所1,住所2,住所3,築年数,地上階,地下,沿線1,駅名1,駅徒歩1,沿線2,駅名2,駅徒歩2,沿線3,駅名3,駅徒歩3,駅徒歩最短
0,B0000001,東京都,北区,田端,32,6,1,ＪＲ山手線,田端駅,6,ＪＲ山手線,西日暮里駅,12.0,東京メトロ千代田線,千駄木駅,16.0,6.0
1,B0000002,東京都,台東区,上野,6,14,1,ＪＲ山手線,秋葉原駅,8,ＪＲ山手線,御徒町駅,5.0,東京メトロ日比谷線,仲御徒町駅,2.0,2.0
2,B0000003,東京都,北区,田端,7,2,1,ＪＲ山手線,駒込駅,9,ＪＲ山手線,田端駅,10.0,ＪＲ山手線,西日暮里駅,14.0,9.0
3,B0000004,東京都,北区,田端,23,5,1,ＪＲ山手線,田端駅,3,ＪＲ山手線,西日暮里駅,6.0,ＪＲ山手線,日暮里駅,17.0,3.0
4,B0000005,東京都,荒川区,東日暮里,13,15,1,ＪＲ山手線,日暮里駅,2,ＪＲ山手線,西日暮里駅,10.0,ＪＲ山手線,上野駅,25.0,2.0

##### __★CHALLENGE４★__
以下に、CHALLENGE４の処理を追加してください。

In [30]:
%%time
import sys
import numpy as np

build_tmp = build.copy()

build_tmp['山手線最寄り駅'] = np.NAN
build_tmp['山徒歩'] = np.NAN

# 沿線1が山手線であれば初期値セット
build_tmp.loc[build_tmp['沿線1'] == 'ＪＲ山手線', '山手線最寄り駅'] = build_tmp['駅名1']
build_tmp.loc[build_tmp['沿線1'] == 'ＪＲ山手線', '山徒歩'] = build_tmp['駅徒歩1']

# 山徒歩が初期値、または沿線2が山徒歩にセットされている駅徒歩より小さければ更新
build_tmp.loc[(build_tmp['沿線2'] == 'ＪＲ山手線') & (build_tmp['山徒歩'].isna() ==True ), '山手線最寄り駅'] = build_tmp['駅名2']
build_tmp.loc[(build_tmp['沿線2'] == 'ＪＲ山手線') & (build_tmp['山徒歩'].isna() ==True ), '山徒歩'] = build_tmp['駅徒歩2']
build_tmp.loc[(build_tmp['沿線2'] == 'ＪＲ山手線') & (build_tmp['山徒歩'] > build_tmp['駅徒歩2'] ) , '山手線最寄り駅'] = build_tmp['駅名2']
build_tmp.loc[(build_tmp['沿線2'] == 'ＪＲ山手線') & (build_tmp['山徒歩'] > build_tmp['駅徒歩2'] ) , '山徒歩'] = build_tmp['駅徒歩2']

# 山徒歩が初期値、または沿線3が山徒歩にセットされている駅徒歩より小さければ更新
build_tmp.loc[(build_tmp['沿線3'] == 'ＪＲ山手線') & (build_tmp['山徒歩'].isna() ==True ), '山手線最寄り駅'] = build_tmp['駅名3']
build_tmp.loc[(build_tmp['沿線3'] == 'ＪＲ山手線') & (build_tmp['山徒歩'].isna() ==True ), '山徒歩'] = build_tmp['駅徒歩3']
build_tmp.loc[(build_tmp['沿線3'] == 'ＪＲ山手線') & (build_tmp['山徒歩'] > build_tmp['駅徒歩3'] ) , '山手線最寄り駅'] = build_tmp['駅名3']
build_tmp.loc[(build_tmp['沿線3'] == 'ＪＲ山手線') & (build_tmp['山徒歩'] > build_tmp['駅徒歩3'] ) , '山徒歩'] = build_tmp['駅徒歩3']

Wall time: 81.3 ms

In [31]:
%%time
import sys
import numpy as np
def yamanote_moyori(row):
    moyori_list = [row[['沿線1','駅名1','駅徒歩1']], row[['沿線2','駅名2','駅徒歩2']], row[['沿線3','駅名3','駅徒歩3']]]
    station = np.NAN
    toho = sys.maxsize

    for moyori in moyori_list:
        ensen, station_tmp, toho_tmp = moyori.values
        if ensen == 'ＪＲ山手線' and toho_tmp < toho:
            station = station_tmp
            toho = toho_tmp
    if toho == sys.maxsize:
        toho = np.NAN
    return pd.Series([station, toho])

build[['山手線駅', '山手線駅徒歩']] =  build[['沿線1','駅名1','駅徒歩1','沿線2','駅名2','駅徒歩2','沿線3','駅名3','駅徒歩3']].apply(yamanote_moyori, axis=1)

Wall time: 1min 20s

##### __（★CHALLENGE４★終わり）__

---
#### 【Question7】２つのデータを結合しよう
---

roomとbuildの2種類のデータがあります。この2つのデータを結合して分析用データを作成します。  
roomの'建物ID'にbuildの'建物ID'を結合することで、roomの各物件の情報に建物の情報を付加することができます。  
  
データを結合する場合は、結合の種類に注意が必要です。どの結合方法が良いかはデータや分析の内容によって異なります。今回は、家賃の傾向や家賃の値段に寄与する要素は何かといった分析を目的としたいため、roomとbuildの両方が揃っているデータを使用していきます。

同じ建物の中に複数の物件が存在する為、roomにある'建物ID'は重複していても良いのですが、  
buildのは1つの建物に1つの'建物ID'、roomは1つの物件に1つの'物件ID'が付与されている仕様です。  
まずはそれぞれのIDが重複していないかを確認してみましょう。

In [32]:
# buildの'建物ID'の<件数>と<重複を除いた値の件数>を出力
print(build['建物ID'].count())
print(build['建物ID'].nunique())

13195
13195

In [33]:
# roomの'物件ID'の<件数>と<重複を除いた値の件数>を出力
print(room['物件ID'].count())
print(room['物件ID'].nunique())

23842
23842

各IDが仕様通り重複していない事が確認できたので、roomとbuildを'建物ID'をキーにして結合し、  
chintaiという名前の結合後DataFrameを作成しましょう。  
結合方法は、roomとbuildの両方に存在するデータのみを結合してください。

In [34]:
# データ結合
# 左側にroom、右側にbuildとなるように内部結合したchintaiデータを作成
chintai = pd.merge(room, build, on='建物ID', how='inner')

# chintaiデータの先頭5行を確認する
chintai.head()

,物件ID,建物ID,物件階,間取り,面積,家賃,管理費,敷金,礼金,平米単価,...,駅徒歩1,沿線2,駅名2,駅徒歩2,沿線3,駅名3,駅徒歩3,駅徒歩最短,山手線駅,山手線駅徒歩
0,R0000001,B0000001,2,44K,552.58,2484000.0,0,0.0,1.0,4495.276702,...,6,ＪＲ山手線,西日暮里駅,12.0,東京メトロ千代田線,千駄木駅,16.0,6.0,田端駅,6.0
1,R0000002,B0000002,7,1K,26.10,100000.0,8000,1.0,1.0,3831.417625,...,8,ＪＲ山手線,御徒町駅,5.0,東京メトロ日比谷線,仲御徒町駅,2.0,2.0,御徒町駅,5.0
2,R0000003,B0000002,8,1K,26.10,99500.0,8000,1.0,1.0,3812.260536,...,8,ＪＲ山手線,御徒町駅,5.0,東京メトロ日比谷線,仲御徒町駅,2.0,2.0,御徒町駅,5.0
3,R0000004,B0000003,1,1LDK,40.12,118000.0,5800,0.0,2.0,2941.176471,...,9,ＪＲ山手線,田端駅,10.0,ＪＲ山手線,西日暮里駅,14.0,9.0,駒込駅,9.0
4,R0000005,B0000004,3,3LDK,89.67,235000.0,0,2.0,0.0,2620.720419,...,3,ＪＲ山手線,西日暮里駅,6.0,ＪＲ山手線,日暮里駅,17.0,3.0,田端駅,3.0

結合済データchintaiを作成できたら、物件IDと建物IDのそれぞれの件数と重複を除いた値の件数を確認しましょう。  
何件結合できたのか、キー重複により件数が増大していないか等を確認します。

In [35]:
# chintaiの'物件ID'の<件数>と<重複を除いた値の件数>を出力
print(chintai['物件ID'].count())
print(chintai['物件ID'].nunique())

23802
23802

In [36]:
# chintaiの'建物ID'の<件数>と<重複を除いた値の件数>を出力
print(chintai['建物ID'].count())
print(chintai['建物ID'].nunique())

23802
12997

それぞれのIDの重複を除いた件数を確認するといずれか片方にしかなく、結合できなかったデータがありそうです。  
実際にそれぞれのデータで何件が結合出来なかったのか、下記を実行して確認してみましょう。  
またどのようなコードになっているか読み解いてみてください。

In [37]:
# ●結合されなかったデータ数の確認
print('room:', room.loc[~(room['物件ID'].isin(chintai['物件ID'].unique())), '物件ID'].count())
print('build:', build.loc[~(build['建物ID'].isin(chintai['建物ID'].unique())), '建物ID'].count())

room: 40
build: 198

---
#### 【Question8】加工したデータをCSVファイルに出力しよう
---

元のデータに加工を行った後、CSVファイルに出力して保管を行ったり、別の分析で流用することもあります。  
加工したデータをchintai.csvという名前のファイルで出力しましょう。  
出力ファイルについて、インデックスは出力しない設定としてください。

In [38]:
# chintaiをchintai.csvファイルとして出力する
chintai.to_csv('chintai.csv', index=False)

■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

---
#### 【CHALLENGE】もう少しデータ加工に挑戦しよう
---

【Question1】～【Question7】で一通りのデータ加工処理を記述しました。  
その後、データ内容の確認や深堀、可視化等を行う中で既存処理の修正や新規処理追加を行うことがあります。  
  
Jupyter Notebookは対話型のインターフェースの為、後ろに書き足していっても自身で実行する順番を気を付ければよいのですが、可読性に欠けます。  
適切な場所に処理を追加・修正しておくほうが、第三者に引き継いだり、時間が経ってから（忘れたころに）再実行する際にミスを防止できます。  
  
以下のCHALLENGE問題では、各問題文を読んだ上で指示に従い、適切な場所に処理を追加・修正を行ってください。  
その際に各CHALLENGEの処理のみを実行するのではなく、処理の繋がりを考えて必要に応じて前後の処理を実行するように気を付けましょう。

##### __CHALLENGE１）地上階を数値に変換しよう__
buildにある「地上階」はその建物が何階建かを表しています。また、roomにある「物件階」はその物件が何階かを表しています。  
建物自体の階数が高いとタワーマンションで、1～3階建だとアパートの可能性が高くなるといったように、建物の階数が高ければ高いど家賃が高くなるといった傾向があるかもしれません。カテゴリカルな値（文字）よりは階数を数値で保有していたほうが良さそうです。  
    ※データ分析の世界では、カテゴリカル値より数値のほうが様々分析を行うことができます。  

    【Question4】にある「★CHALLENGE１★」の場所に以下の処理を追加してください。  
```
     １．buildの「地上階」を数値に変換する  
     　例）'3階建' →　3
     ２．roomの「物件階」を数値に変換する
     　例）'4階' →　4
```

##### __【＋α】データフレーム値の置換方法__
値の置換は`loc`を上手く使って置換する方法以外にも、`replace()`を使用する方法もあります。     

`df['A'].str.replace('B','C')` # dfの'A'列にある文字列'B'を'C'に置き換える。数値置換不可。置換えは部分一致。  
`df.replace('B', 'C')` # dfの全ての要素に対して'B'を'C'に置き換える。数値置換可。置換えは完全一致。部分一致は'regex=True'オプションを指定。  
`df.replace({'A':{'B':'C'}},regex=True)` # dfの'A'列にある文字列'B'を'C'に置き換える。'regex=True'オプションにより部分一致。

In [39]:
# ●(ちょっと確認)地上階ごとに家賃の平均を算出し、平均家賃を降順で表示して確認
chintai.groupby(by='地上階')['家賃'].mean().sort_values(ascending=False)

地上階
33    978833.333333
35    687000.000000
43    549000.000000
57    482000.000000
52    465000.000000
34    463055.555556
44    416465.116279
38    402777.777778
21    389328.767123
47    382115.384615
37    377525.842697
40    348376.811594
55    344125.000000
25    336025.000000
20    329975.609756
49    327352.941176
48    326946.428571
42    324900.000000
56    323921.568627
23    305373.493976
46    293187.500000
26    291714.285714
36    272475.000000
60    271625.000000
39    270650.000000
32    268512.820513
31    267782.608696
28    262268.292683
29    258326.530612
22    239304.761905
50    239000.000000
24    238954.347826
16    236549.180328
30    216542.372881
19    212436.363636
27    208214.285714
18    187742.424242
17    179900.000000
13    145986.538462
14    144328.639618
10    139509.255159
15    139378.053704
7     137292.562814
12    135667.953431
6     133118.242492
9     130557.180385
8     123905.072637
11    120556.847739
5     115884.136933
4     111089.134461
3     107318.730597
1     100388.888889
2      75363.770977
Name: 家賃, dtype: float64

##### __CHALLENGE２）地下をあり／なしのフラグにしよう__
buildにある「地下」について、【Question4】で欠損値を'地下0'に置き換えました。    
CHALLENGE１）と同じように、地下についても数値で持っておくほうが良いかなと検討しました。  
しかし賃貸物件の地下は何階分あるかよりも、あるのかないのかというフラグでも良いかもしれません。（本来ならデータや専門知識から判断するもの）  
今回は地下については有無の1,0でフラグにすることにします。  

    【Question4】にある「★CHALLENGE２★」の場所に以下の処理を実施・追加してください。  
```
     １．【Question4】の２）で欠損値を補完している処理をコメントアウトする 
     ２．既に欠損補完処理（'地下0'に置き換え）をしているので、【Question2】build.csvの読込～★CHALLENGE２★までを再実行  
     ３．buildの「地下」を欠損していなかったなら1に、欠損なら0の数値に変換する
     　例）'4階' →　'1'　、　NaN →　'0'
```

##### __【＋α】欠損していない判定__
`isnull()`は欠損値だとTrueを返しますが、非欠損値でTrueを返す`notnull()`というのもあります。     

`df['A'].str.replace('B','C')` # dfの'A'列にある文字列'B'を'C'に置き換える。数値置換不可。置換えは部分一致。  
`df.replace('B', 'C')` # dfの全ての要素に対して'B'を'C'に置き換える。数値置換可。置換えは完全一致。部分一致は'regex=True'オプションを指定。  
`df.replace({'A':{'B':'C'}},regex=True)` # dfの'A'列にある文字列'B'を'C'に置き換える。'regex=True'オプションにより部分一致

##### __CHALLENGE３）山手線駅の沿線名を修正しよう__
buildにある「沿線1」、「沿線2」、「沿線3」について、山手線の駅であっても他の沿線で表記されているものもある。    
今回は山手線の駅であれば、沿線を'ＪＲ山手線'としたい。  

    【Question4】にある「★CHALLENGE３★」の場所に以下の処理を追加してください。  
```
    １．「★CHALLENGE２★」から「★CHALLENGE３★」の直前までの処理を実行する
    ２．「駅名1」が山手線駅で、かつ「沿線1」が'ＪＲ山手線'でない場合、'ＪＲ山手線'に変更
     　　「沿線2」、「沿線３」についても同様の処理を実施  
       　※処理上は　「沿線1」が'ＪＲ山手線'でも、それ以外でも一律で置換すればよいが、 
        　　今回は、学習を目的として＆条件を使って実施する  
```

山手線の駅かどうかは下記を利用
```
yamanote = ['大崎駅', '五反田駅', '目黒駅', '恵比寿駅', '渋谷駅', '原宿駅', '代々木駅', 
            '新宿駅', '新大久保駅', '高田馬場駅', '目白駅', '池袋駅', '大塚駅', '巣鴨駅', 
            '駒込駅', '田端駅', '西日暮里駅', '日暮里駅', '鶯谷駅', '上野駅', '御徒町駅', '秋葉原駅', 
            '神田駅', '東京駅', '有楽町駅', '新橋駅', '浜松町駅', '田町駅', '品川駅']
```

##### __CHALLENGE４）★難易度高★最寄りの山手線駅を特定しよう__
buildの最寄り駅を見てい見ると以下のことがわかりました。  
* 駅名1には必ずしも山手線駅が入っているとは限らない
* 駅名1～3が必ずしも徒歩距離が近い順番で入っているとは限らない
* 駅名1～3の中に複数の山手線駅が入っている場合もある  
  
上記を踏まえて、物件で最も近い山手線駅を特定してみましょう。

    【Question5】にある「★CHALLENGE４★」の場所に以下の処理を追加してください。  
```
    １．「★CHALLENGE３★」から「★CHALLENGE４★」の直前までの処理を実行する
    ２．物件の最寄り駅の中で山手線駅で最も近い駅と徒歩距離を判定し新規項目として追加する。
     　　最も近い山手線駅は「山手線駅」という変数で追加
         その最も近い山手線駅の徒歩距離を「山手線駅徒歩」という変数で追加
         ※最も近い山手線駅が2つ抽出されたら、割り切りで駅名1>駅名2>駅名3の順で優先させる
```

> 処理が難しいと思った人は「Challenge4」フォルダの中に処理の解答例を2つ用意しています。  
> どのように処理されているか読み解いてみましょう。  
> また書き方によって実行時間は大きく変わります。2つの処理をそれぞれ実行してみて、時間の違いを確認しましょう。
> ※実際に採用する処理は可読性の実行時間を加味して選択してください。

##### __CHALLENGE５）最後に全ての処理が問題なく行えるか通して処理を実行してみましょう__
CHALLENGE問題で処理を追加・修正を行ったので、最初から最後まで正しく処理が実行できるか確認してみましょう。

##### __EXTRA）他にも加工できそうなポイントがあれば実施してみましょう__
例えば建物の最上階の物件であれば、最上階フラグを作成する等、加工できそうなアイディアがあればチャレンジしましょう。

■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■END）